export const bookingsMockData = [
  {
    _id: 'booking1',
    user: 'user1',
    date: new Date('2024-06-10T10:00:00Z'),
    status: 'booked',
    training: {
      _id: 'training1',
      datetime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      duration: 60,
      spots_taken: 5,
      spots_total: 10,
      trainer_id: {
        _id: 'trainer1',
        fullName: 'Anna Ivanova',
        experience: 5,
        specialization: 'Hatha Yoga',
        about: 'Experienced Hatha yoga trainer',
        photo: 'https://example.com/photos/anna.jpg',
      },
      yogaStyle_id: {
        _id: 'style1',
        title: 'Hatha',
        image: 'https://example.com/images/hatha.jpg',
        duration: 60,
        trainer: 'trainer1',
        description: 'Gentle and slow yoga style',
      },
      type: 'group',
      price: 15,
      priceId: 'price_001',
    },
  },
  {
    _id: 'booking2',
    user: 'user1',
    date: new Date('2024-05-01T12:00:00Z'),
    status: 'completed',
    training: {
      _id: 'training2',
      datetime: new Date('2024-05-01T12:00:00Z'),
      duration: 45,
      spots_taken: 10,
      spots_total: 10,
      trainer_id: {
        _id: 'trainer2',
        fullName: 'Ivan Petrov',
        experience: 10,
        specialization: 'Vinyasa Yoga',
        about: 'Expert in dynamic Vinyasa flow',
        photo: 'https://example.com/photos/ivan.jpg',
      },
      yogaStyle_id: {
        _id: 'style2',
        title: 'Vinyasa',
        image: 'https://example.com/images/vinyasa.jpg',
        duration: 45,
        trainer: 'trainer2',
        description: 'Dynamic and flowing yoga style',
      },
      type: 'private',
      price: 25,
      priceId: 'price_002',
    },
  },
  {
    _id: 'booking3',
    user: 'user1',
    date: new Date('2024-04-01T09:00:00Z'),
    status: 'cancelled',
    training: {
      _id: 'training3',
      datetime: new Date('2024-04-10T09:00:00Z'),
      duration: 60,
      spots_taken: 3,
      spots_total: 15,
      trainer_id: {
        _id: 'trainer3',
        fullName: 'Elena Smirnova',
        experience: 7,
        specialization: 'Ashtanga Yoga',
        about: 'Passionate Ashtanga teacher',
        photo: 'https://example.com/photos/elena.jpg',
      },
      yogaStyle_id: {
        _id: 'style3',
        title: 'Ashtanga',
        image: 'https://example.com/images/ashtanga.jpg',
        duration: 60,
        trainer: 'trainer3',
        description: 'Powerful and disciplined yoga style',
      },
      type: 'group',
      price: 20,
      priceId: 'price_003',
    },
  },
];
