export const plansMock = [
  {
    type: 'pack',
    title: '5-Class pack',
    price: 100,
    description: 'Flexible schedules or occasional visitors',
    priceId: 'price_1RaDrbHCX17lsTRpRlbNr3y4',
    trainingsCoiunt: 5,
  },
  {
    type: 'pack',
    title: '10-Class pack',
    price: 220,
    description: 'Flexible schedules or occasional visitors',
    priceId: 'price_1RaDrxHCX17lsTRpida8URQV',
    trainingsCoiunt: 10,
  },
  {
    type: 'unlimited',
    title: '3 months',
    price: 300,
    description: 'Includes weekly sessions and progress tracking.',
    priceId: 'price_1RaDkUHCX17lsTRpcsc0qhd2',
    trainingsCoiunt: 3,
  },
  {
    type: 'unlimited',
    title: '6 months',
    price: 600,
    description: 'Better value for long-term learners.',
    priceId: 'price_1RaDkUHCX17lsTRpcsc0qhd2',
    trainingsCoiunt: 6,
  },
  {
    type: 'unlimited',
    title: '12 months',
    price: 1000,
    description: 'Best offer for dedicated clients.',
    priceId: 'price_1RaDqYHCX17lsTRp5W98G0sp',
    trainingsCoiunt: 12,
  },
  {
    type: 'one',
    title: '1 session',
    price: 25,
    description: 'Try one individual session without commitment.',
    priceId: 'price_1RaEHAHCX17lsTRpYB12g57y',
  },
];
